repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-added-large-files
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix]
    - id: trailing-whitespace
